#############################################################################
# Makefile for building: sudoku
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  sudoku.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile sudoku.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sudoku1.0.0
DISTDIR = /home/rad/sudoku/.tmp/sudoku1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		window.cpp \
		board.cpp moc_window.cpp
OBJECTS       = main.o \
		window.o \
		board.o \
		moc_window.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		sudoku.pro window.h main.cpp \
		window.cpp \
		board.cpp
QMAKE_TARGET  = sudoku
DESTDIR       = 
TARGET        = sudoku


first: all
####### Build rules

sudoku:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sudoku.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		sudoku.pro
	$(QMAKE) -o Makefile sudoku.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
sudoku.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile sudoku.pro

qmake_all: FORCE


all: Makefile sudoku

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents window.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp window.cpp board.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp
moc_window.cpp: window.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainertools_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QPushButton \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qpushbutton.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QGridLayout \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qgridlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qboxlayout.h \
		board.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rad/sudoku/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rad/sudoku -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include window.h -o moc_window.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp window.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainertools_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QPushButton \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qpushbutton.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QGridLayout \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qgridlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qboxlayout.h \
		board.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

window.o: window.cpp window.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainertools_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtabwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qicon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QPushButton \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qpushbutton.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QGridLayout \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qgridlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlayout.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qboxlayout.h \
		board.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QLineEdit \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qlineedit.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qframe.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpen.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/QValidator \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvalidator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregularexpression.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

board.o: board.cpp board.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o board.o board.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

